name: Create a Release

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      confirm:
        description: 'Confirm Release (Dry Run by default)'
        type: boolean
        required: false
        default: false
      release_name:
        description: 'Release branch name (eg: sprint-10)'
        type: string
        required: true
        default: 'sprint-'
      transcreation-api-version:
        description: '[!] Transcreation API version'
        type: string
        required: false
        default: ''
      tracking-api-version:
        description: '[!] Tracking API version'
        type: string
        required: false
        default: ''
      manage-api-version:
        description: '[!] Manage API version'
        type: string
        required: false
        default: ''
      manage-ui-version:
        description: '[!] Manage UI version'
        type: string
        required: false
        default: ''

jobs:
  create-a-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for AWS access
      contents: write # Required for creating branches, commits, and tags
      pull-requests: write # Required for creating pull requests

    steps:     
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for accurate changelog generation and nx release

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies and dump versions
        run: |
          npm ci
          npx nx report

      - name: Determine release branch names
        id: variables
        run: |
          echo "feature_branch=feature/release-${{ github.event.inputs.release_name }}" >> $GITHUB_OUTPUT
          echo "release_branch=release/${{ github.event.inputs.release_name }}" >> $GITHUB_OUTPUT

      # Create temporary feature branch from main, that will be used to raise versions
      - name: Create feature branch feature/release-${{ github.event.inputs.release_name }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git pull origin main
          git checkout -b ${{ steps.variables.outputs.feature_branch }}
      
      # Validate that we have release versions
      - name: Validate NX Release
        id: validate_nx_release
        run: |
          npx nx release version --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create versions and Git Tags
      - name: Check version overrides
        id: validate_version
        if: steps.validate_nx_release.outcome == 'success' && github.event.inputs.confirm == 'true'
        run: |
          TRANSCREATION_API="${{ github.event.inputs.transcreation-api-version }}"
          TRACKING_API="${{ github.event.inputs.tracking-api-version }}"
          MANAGE_API="${{ github.event.inputs.manage-api-version }}"
          MANAGE_UI="${{ github.event.inputs.manage-ui-version }}"
          ALL_VALID=true          

          if [[ ! -z "$TRANSCREATION_API" ]]; then
            if [[ "$TRANSCREATION_API" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Provided 'transcreation-api-version: $TRANSCREATION_API' is a valid semantic version."
            else
              echo "Provided 'transcreation-api-version: $TRANSCREATION_API' is NOT a valid semantic version.  It must be in the format X.Y.Z (e.g., 1.2.3)."
              ALL_VALID=false
            fi
          fi
          if [[ ! -z "$TRACKING_API" ]]; then
            if [[ "$TRACKING_API" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Provided 'tracking-api-version: $TRACKING_API' is a valid semantic version."
            else
              echo "Provided 'tracking-api-version: $TRACKING_API' is NOT a valid semantic version.  It must be in the format X.Y.Z (e.g., 1.2.3)."
              ALL_VALID=false
            fi
          fi
          if [[ ! -z "$MANAGE_API" ]]; then
            if [[ "$MANAGE_API" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Provided 'manage-api-version: $MANAGE_API' is a valid semantic version."
            else
              echo "Provided 'manage-api-version: $MANAGE_API' is NOT a valid semantic version.  It must be in the format X.Y.Z (e.g., 1.2.3)."
              ALL_VALID=false
            fi
          fi
          if [[ ! -z "$MANAGE_UI" ]]; then
            if [[ "$MANAGE_UI" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Provided 'manage-ui-version: $MANAGE_UI' is a valid semantic version."
            else
              echo "Provided 'manage-ui-version: $MANAGE_UI' is NOT a valid semantic version.  It must be in the format X.Y.Z (e.g., 1.2.3)."
              ALL_VALID=false
            fi
          fi

          if [[ "$ALL_VALID" == "false" ]]; then
            echo "::set-output name=valid::false"
            exit 1 # Fail the workflow if any version is invalid
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create versions and Git Tags of the rest of projects
      - name: Run NX Release
        if: steps.validate_version.outcome == 'success' && github.event.inputs.confirm == 'true'
        id: nx_release
        run: |
          if [[ ! -z "${{ github.event.inputs.transcreation-api-version }}" ]]; then
            npx nx release -p transcreation-api --skip-publish ${{ github.event.inputs.transcreation-api-version }}
          fi
          if [[ ! -z "${{ github.event.inputs.tracking-api-version }}" ]]; then
            npx nx release -p tracking-api --skip-publish ${{ github.event.inputs.tracking-api-version }}
          fi
          if [[ ! -z "${{ github.event.inputs.manage-api-version }}" ]]; then
            npx nx release -p manage-api --skip-publish ${{ github.event.inputs.manage-api-version }}
          fi
          if [[ ! -z "${{ github.event.inputs.manage-ui-version }}" ]]; then
            npx nx release -p nx-repository --skip-publish ${{ github.event.inputs.manage-ui-version }}
          fi
          npx nx release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create release branch and push changes to GitHub
      - name: Create release branch release/${{ github.event.inputs.release_name }}
        if: steps.nx_release.outcome == 'success' && github.event.inputs.confirm == 'true'
        run: |
          git checkout ${{ steps.variables.outputs.feature_branch }}
          git push origin ${{ steps.variables.outputs.feature_branch }} --tags
          git checkout -b ${{ steps.variables.outputs.release_branch }}
          git push origin ${{ steps.variables.outputs.release_branch }} --tags

      # Create a Pull Request from temporary feature branch, back to main
      - name: Create Pull Request
        if: steps.nx_release.outcome == 'success' && github.event.inputs.confirm == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            //const github = require('@actions/github');
            const core = require('@actions/core');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = 'main';
            const head = '${{ steps.variables.outputs.feature_branch }}';
            const title = `Release: ${{ github.event.inputs.release_name }}`;
            const body = `Automated release pull request for version updates.`;
            const reviewers = ['jakubsemecky-vml', 'krejcit'];

            try {
              // Create Pull Request
              const { data: pullRequest } = await github.rest.pulls.create({
                owner,
                repo,
                title,
                head,
                base,
                body,
              });
              core.info(`Pull request created: ${pullRequest.html_url}`);

              // Request reviewers
              await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number: pullRequest.number,
                reviewers: reviewers
              });
              core.info(`Reviewers requested: ${reviewers.join(', ')}`);

            } catch (error) {
              core.setFailed(`Failed to create pull request: ${error.message}`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dry Run Message
        if: github.event.inputs.confirm != 'true'
        run: |
          echo "Release not confirmed, running dry run mode!"
          echo "No commits, tags, or pull requests were created."
